version: '3.3'

services:
  db:
    image: postgres:14
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=telegram_bot
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "timeout", "10s", "pg_isready", "-U", "postgres"]
      interval: 20s
      timeout: 10s
      retries: 5
    entrypoint:
      - sh
      - -c
      - "while ! pg_isready -U postgres; do sleep 2; done; python -c 'from database import init_db; init_db()'"

  bot:
    build: .
    volumes:
      - ./:/app
    depends_on:
      - db
    entrypoint: ["python", "app.py"]
    env_file:
      - .env
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
